#!/bin/bash
# 20150505 This script will check for the existance of and report the size of fastq files in the seqware metadatabase (from the seqware file report) for the run dir specified.
# This script is useful as a check when cleaning up the run dir
# Why not Perl? LONG LIVE THE BASH SHELL!

#Color codes
#export COLOR_NC='\e[0m' # No Color
#export COLOR_WHITE='\e[1;37m'
#export COLOR_BLACK='\e[0;30m'
#export COLOR_BLUE='\e[0;34m'
#export COLOR_LIGHT_BLUE='\e[1;34m'
#export COLOR_GREEN='\e[0;32m'
#export COLOR_LIGHT_GREEN='\e[1;32m'
#export COLOR_CYAN='\e[0;36m'
#export COLOR_LIGHT_CYAN='\e[1;36m'
#export COLOR_RED='\e[0;31m'
#export COLOR_LIGHT_RED='\e[1;31m'
#export COLOR_PURPLE='\e[0;35m'
#export COLOR_LIGHT_PURPLE='\e[1;35m'
#export COLOR_BROWN='\e[0;33m'
#export COLOR_YELLOW='\e[1;33m'
#export COLOR_GRAY='\e[0;30m'
#export COLOR_LIGHT_GRAY='\e[0;37m'

# Esc[value;...;valuem
# 0 all attrib off
# 1 bold
# 4 underscore
# 

# Get the current directory name if a target run dir is not provided
if [ -z "$1" ]; then
    FILE=${PWD##*/}
else
    FILE="$1"
fi

# Use the most current seqware_files_report if one is not provided
if [ -z "$2" ];then
    SOURCE="$(ls -Art /.mounts/labs/seqprodbio/private/backups/hsqwprod-db/seqware* | tail -n 1)"
    #SOURCE="/u/tbeck/tmp/seqware_files_report_20150504-01:02.gz"
else
    #This allows you to run this script from anywhere even if you passed a local seqware_files_report
    SOURCE="`readlink -f $2`"
fi



# Report a header
# Note we also create a local report file so you can visually inspect and keep a log at the same time
printf "Source file: %s   Look for: %s   Date: %s \n" $SOURCE $FILE $(date +%Y%m%dT%H%M%S) | tee seqwareFastqFiles.txt

# Read carefully. Note for the terminal output the file size is highlighted for easy visual check. The files are sorted by filename so R1 and R2 should be paried and ordered by increasing lane
#zgrep $FILE $SOURCE | grep BCLToFastq | awk -F'\t' '{print $47}' | xargs --no-run-if-empty ls -lalh | sort -k9 | awk -F' ' '{sep=""; for (i=1; i<=NF; i++) {if (i==5) printf("[1;37m%s%s[0m",sep,$i); else printf("%s%s",sep,$i); sep=OFS}; printf("\n") }' | tee >(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" >> seqwareFastqFiles.txt)
zgrep $FILE $SOURCE | grep CASAVA | awk -F'\t' '{print $47}' | xargs --no-run-if-empty ls -lalh | sort -k9 | awk -F' ' '{
sep="";
for (i=1; i<=NF; i++) {
    if (i==5)
        printf("[1;37m%s%s[0m",sep,$i);
    else { 
        gsub(/L..._R./, "[1;37m&[0m");
        printf("%s%s",sep,$i);
    }
    sep=OFS
};
printf("\n")
 }' | tee >(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" >> seqwareFastqFiles.txt)

## The idea for this code was to query JIRA with the run name and generate a report for that as well
## Would be best to do the same thing for LIMS
# This works kinda - need to improve:
# auth - don't add password each time
# response - don't want JSON I think
# curl -k -D- -u tbeck -X GET -H "Content-Type: application/json" https://jira.oicr.on.ca/rest/api/2/search?jql=project=SEQPRODBIO

