#!/bin/bash
# Outputs sorted list - easy to see if one dir has not been cleaned
find . -maxdepth 2 -name 'CLEANED.TIM' | xargs -I'{}' bash -c "echo \"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\"; echo {}; cat {}" | less

