#!/bin/bash
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee cleanIntensities.txt)
exec 2>&1

printf "%s TIMESTAMP\n" `date +%Y%m%dT%H%M%S`
THISPATH=`pwd`
THISDIR=`basename $THISPATH`
printf "Processing: %s\n" $THISPATH
#if echo $1 > awk '$1 !~ /[0-9]{6}_[A-Za-z]{1}[0-9]{3,5}_[0-9]{4}_[A-Z0-9]{10}/ {exit 1}'; then
#       printf "\nThis dir \'%s\' does not look like an illumina run directory\n\n" $1
#       exit 1
#fi
# Nice use of bash regex's
#Bustard1.8.0_19-01-2011_mchan 
#if [[ ! $THISDIR =~ Bustard[0-9a-z.]{5,7}_[0-9]{2}-[0-9]{2}-[0-9]{4}_[a-zA-Z]{2,8} ]];then
if [[ ! $THISDIR =~ Intensities ]];then
        printf "The dir $THISDIR does not look like an illumina Intensities directory\n\n";
        exit 1;
fi
# Bash control operators
#command1 && command2
#   command2 is executed if, and only if, command1 returns an exit status of zero.
#An OR list has the form
#command1 || command2
#   command2 is executed if and only if command1 returns a non-zero exit status.  The return status of AND and OR lists is the exit status of the last command executed in the list.

set -x
rm -rf L001 L002 L003 L004 L005 L006 L007 L008
rm -rf ./Offsets
rm -rf *_pos.txt
set +x
printf "%s TIMESTAMP\n" `date +%Y%m%dT%H%M%S`
